namespace NovelWriter.Wpf.Services;

/// <summary>
/// 한글/영문 UI 텍스트를 제공합니다.
/// </summary>
public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> Korean = new Dictionary<string, string>
    {
        ["TitlePlaceholder"] = "문서 제목",
        ["OpenButton"] = "불러오기",
        ["ExportButton"] = "DOCX 내보내기",
        ["SaveButton"] = "저장",
        ["AiFixButton"] = "AI 오타 보정",
        ["FocusButton"] = "집중 모드",
        ["FileMenu"] = "파일",
        ["ViewMenu"] = "보기",
        ["ThemeMenu"] = "테마",
        ["ThemeDark"] = "다크",
        ["ThemeLight"] = "라이트",
        ["ThemeCustom"] = "커스텀",
        ["Language"] = "언어",
        ["LanguageKorean"] = "한국어",
        ["LanguageEnglish"] = "English",
        ["AiModelLabel"] = "AI 모델",
        ["ToolbarIconSizeLabel"] = "툴바 아이콘 크기",
        ["ChatFontSizeLabel"] = "AI 어시스턴트 폰트 크기",
        ["ChatBackgroundLabel"] = "AI 어시스턴트 배경색",
        ["EditorFontSizeLabel"] = "편집기 폰트 크기",
        ["CustomThemeLabel"] = "테마 커스텀 (직접 색 지정)",
        ["CustomBackgroundLabel"] = "커스텀 배경색",
        ["CustomForegroundLabel"] = "커스텀 글자색",
        ["AiSetupTitle"] = "AI 모델 준비",
        ["AiSetupChecking"] = "AI 환경을 확인하는 중입니다...",
        ["AiSetupOllamaMissing"] = "Ollama가 실행되고 있지 않습니다. Ollama를 설치하고 실행한 뒤 다시 확인해 주세요.",
        ["AiSetupModelMissing"] = "'{0}' 모델이 설치되어 있지 않습니다. 지금 다운로드할까요? (수 GB 용량으로 시간이 걸릴 수 있습니다)",
        ["AiSetupPreparing"] = "다운로드를 준비하는 중입니다...",
        ["AiSetupDownloading"] = "모델 다운로드 중... {0}%",
        ["AiSetupDownloadFailed"] = "다운로드에 실패했습니다. 다시 시도해 주세요.",
        ["AiSetupDownloadButton"] = "다운로드",
        ["AiSetupOpenOllama"] = "Ollama 설치 페이지 열기",
        ["AiSetupRetry"] = "다시 확인",
        ["AiSetupDismiss"] = "나중에",
        ["AiSetupCancel"] = "취소",
        ["AiReady"] = "AI 모델 준비 완료",
        ["ReferenceTitle"] = "참고자료",
        ["ReferenceOpenFolder"] = "폴더 열기",
        ["ReferenceRefresh"] = "새로고침",
        ["ReferenceEmpty"] = "참고자료 폴더를 열어 .md 파일(시놉시스·캐릭터 설정 등)을 표시하세요.",
        ["ChatTitle"] = "AI 어시스턴트",
        ["ChatInputHint"] = "질문을 입력하세요...",
        ["ChatEmpty"] = "무엇이든 물어보세요. 줄거리 아이디어, 캐릭터 설정, 문장 다듬기 등을 도와드립니다.",
        ["ChatFailed"] = "응답을 받지 못했습니다. AI 서버(Ollama) 상태를 확인해 주세요.",
        ["GoalLabel"] = "일일 목표 단어수",
        ["Stats"] = "통계",
        ["Word"] = "단어",
        ["Character"] = "문자",
        ["Page"] = "페이지",
        ["Paragraph"] = "단락",
        ["Sentence"] = "문장",
        ["Progress"] = "진행률",
        ["Saved"] = "저장 완료",
        ["AutoSaved"] = "자동 저장 완료",
        ["AiFixed"] = "오타 자동 보정 완료",
        ["AiChecking"] = "현재 페이지 오타를 검사하는 중...",
        ["TyposFound"] = "오타 {0}개를 붉은 줄로 표시했습니다. (오타를 우클릭하면 교정)",
        ["NoTypos"] = "발견된 오타가 없습니다",
        ["SpellDictMissing"] = "한국어 사전을 찾을 수 없어 맞춤법 검사를 건너뜁니다.",
        ["IgnoreWord"] = "무시",
        ["AddToUserDictionary"] = "사전에 추가",
        ["NoSuggestions"] = "추천 없음",
        ["ContextCheck"] = "AI 문맥 검사",
        ["AiContextChecking"] = "AI 문맥을 검사하는 중...",
        ["ContextFound"] = "문맥 오류 {0}개를 파란 줄로 표시했습니다. (우클릭하면 교정)",
        ["NoContextIssues"] = "문맥 오류가 없습니다",
        ["SaveAsButton"] = "다른 이름으로 저장",
        ["NewDocument"] = "새 문서",
        ["NewDocumentDone"] = "새 문서를 시작했습니다",
        ["SettingsMenu"] = "설정",
        ["SettingsTitle"] = "설정",
        ["AutoSaveLabel"] = "자동 저장 사용",
        ["AutoSaveIntervalLabel"] = "자동 저장 주기(초)",
        ["MenuFontSizeLabel"] = "메뉴 폰트 크기",
        ["ReferenceFontSizeLabel"] = "참고자료 폰트 크기",
        ["ReferenceColorLabel"] = "참고자료 글자 색 (예: #FFDDDDDD)",
        ["SettingsSave"] = "저장",
        ["SettingsClose"] = "닫기",
        ["Opened"] = "파일 불러오기 완료",
        ["OpenFailed"] = "파일 불러오기에 실패했습니다"
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["TitlePlaceholder"] = "Document title",
        ["OpenButton"] = "Open",
        ["ExportButton"] = "Export DOCX",
        ["SaveButton"] = "Save",
        ["AiFixButton"] = "AI typo fix",
        ["FocusButton"] = "Focus mode",
        ["FileMenu"] = "File",
        ["ViewMenu"] = "View",
        ["ThemeMenu"] = "Theme",
        ["ThemeDark"] = "Dark",
        ["ThemeLight"] = "Light",
        ["ThemeCustom"] = "Custom",
        ["Language"] = "Language",
        ["LanguageKorean"] = "Korean",
        ["LanguageEnglish"] = "English",
        ["AiModelLabel"] = "AI Model",
        ["ToolbarIconSizeLabel"] = "Toolbar icon size",
        ["ChatFontSizeLabel"] = "AI assistant font size",
        ["ChatBackgroundLabel"] = "AI assistant background",
        ["EditorFontSizeLabel"] = "Editor font size",
        ["CustomThemeLabel"] = "Custom theme (pick colors)",
        ["CustomBackgroundLabel"] = "Custom background",
        ["CustomForegroundLabel"] = "Custom text color",
        ["AiSetupTitle"] = "AI Model Setup",
        ["AiSetupChecking"] = "Checking the AI environment...",
        ["AiSetupOllamaMissing"] = "Ollama is not running. Please install and start Ollama, then check again.",
        ["AiSetupModelMissing"] = "The '{0}' model is not installed. Download it now? (Several GB; this may take a while.)",
        ["AiSetupPreparing"] = "Preparing the download...",
        ["AiSetupDownloading"] = "Downloading model... {0}%",
        ["AiSetupDownloadFailed"] = "Download failed. Please try again.",
        ["AiSetupDownloadButton"] = "Download",
        ["AiSetupOpenOllama"] = "Open Ollama install page",
        ["AiSetupRetry"] = "Check again",
        ["AiSetupDismiss"] = "Later",
        ["AiSetupCancel"] = "Cancel",
        ["AiReady"] = "AI model ready",
        ["ReferenceTitle"] = "References",
        ["ReferenceOpenFolder"] = "Open folder",
        ["ReferenceRefresh"] = "Refresh",
        ["ReferenceEmpty"] = "Open a reference folder to show .md files (synopsis, character notes, etc.).",
        ["ChatTitle"] = "AI Assistant",
        ["ChatInputHint"] = "Type your question...",
        ["ChatEmpty"] = "Ask me anything — plot ideas, character development, phrasing, and more.",
        ["ChatFailed"] = "No response received. Please check the AI server (Ollama).",
        ["GoalLabel"] = "Daily word goal",
        ["Stats"] = "Stats",
        ["Word"] = "Words",
        ["Character"] = "Characters",
        ["Page"] = "Pages",
        ["Paragraph"] = "Paragraphs",
        ["Sentence"] = "Sentences",
        ["Progress"] = "Progress",
        ["Saved"] = "Saved",
        ["AutoSaved"] = "Autosaved",
        ["AiFixed"] = "AI typo fix completed",
        ["AiChecking"] = "Checking typos on the current page...",
        ["TyposFound"] = "Marked {0} typo(s) with red underline. (Right-click a typo to fix)",
        ["NoTypos"] = "No typos found",
        ["SpellDictMissing"] = "Korean dictionary not found; spell check is skipped.",
        ["IgnoreWord"] = "Ignore",
        ["AddToUserDictionary"] = "Add to dictionary",
        ["NoSuggestions"] = "No suggestions",
        ["ContextCheck"] = "AI context check",
        ["AiContextChecking"] = "Checking context with AI...",
        ["ContextFound"] = "Marked {0} context issue(s) with blue underline. (Right-click to fix)",
        ["NoContextIssues"] = "No context issues found",
        ["SaveAsButton"] = "Save As",
        ["NewDocument"] = "New document",
        ["NewDocumentDone"] = "Started a new document",
        ["SettingsMenu"] = "Settings",
        ["SettingsTitle"] = "Settings",
        ["AutoSaveLabel"] = "Enable auto-save",
        ["AutoSaveIntervalLabel"] = "Auto-save interval (sec)",
        ["MenuFontSizeLabel"] = "Menu font size",
        ["ReferenceFontSizeLabel"] = "Reference font size",
        ["ReferenceColorLabel"] = "Reference text color (e.g. #FFDDDDDD)",
        ["SettingsSave"] = "Save",
        ["SettingsClose"] = "Close",
        ["Opened"] = "File opened",
        ["OpenFailed"] = "Failed to open file"
    };

    /// <summary>
    /// 키에 해당하는 다국어 문자열을 반환합니다.
    /// </summary>
    /// <param name="languageCode">언어 코드입니다.</param>
    /// <param name="key">텍스트 키입니다.</param>
    /// <returns>해당 언어 문자열입니다.</returns>
    public string Get(string languageCode, string key)
    {
        var table = languageCode.StartsWith("ko", StringComparison.OrdinalIgnoreCase) ? Korean : English;
        return table.TryGetValue(key, out var value) ? value : key;
    }
}
